query totara_api_clients($input: totara_api_clients_input!) {
  clients: totara_api_clients(input: $input) {
    items {
      __typename
      id
      name(format: PLAIN)
      service_account {
        user {
          __typename
          id
          fullname
        }
        is_valid
        status
      }
      description(format: HTML)
      oauth2_client_providers {
        id
        client_id
        client_secret
      }
      status
      active_tokens
    }
    total
    next_cursor
  }
}
