"""
Query type to page information
"""
type mod_page_page implements totara_mobile_download_activity {
  """
  Course module id
  """
  id: core_id!
  """
  Module id
  """
  instanceid: core_id!
  """
  The name of the page
  """
  name: String!
  """
  The description of the page
  """
  intro(format: core_format = HTML): String
  """
  The description format
  """
  introformat: core_format
  """
  File attachments
  """
  attachments: [totara_mobile_download_attachment_info]!
  """
  The URL to follow to view this module
  """
  viewurl: String!
  """
  Page content
  """
  content(format: core_format = HTML): String
  """
  Page content format
  """
  contentformat: core_format
  """
  Last modified time
  """
  timemodified: core_date
  """
  Whether the course module displays the description or not
  """
  showdescription: Boolean
  """
  The completion settings of the course module
  """
  completion: String
  """
  Whether completion is enabled or not for the course module
  """
  completionenabled: Boolean!
  """
  The completion status of the current user in the course module
  """
  completionstatus: String
  """
  The total number of download file size
  """
  downloadsize: Int!
}

extend type Query {
  """
  Query to get downloadable page information
  """
  mod_page_download(
    input: totara_mobile_download_activity_input!
  ): mod_page_page!
}
extend type Mutation {
  """
  Save page completion
  """
  mod_page_sync_completion(
    input: totara_mobile_sync_completion_input!
  ): totara_mobile_sync_completion_result!
}
