query mobile_findlearning_view_catalog($pointer: Int) {
  catalogPage: mobile_findlearning_view_catalog(limit_from: $pointer) {
    maxCount: max_count
    pointer: limit_from
    finalPage: final_records
    items {
      id
      itemid
      itemType: item_type
      title
      mobileImage: image_url
      viewUrl: view_url
      summary(format: MOBILE)
      summaryFormat: summary_format
      progress_bar_enabled
      progress_bar {
        progress
      }
      native: mobile_coursecompat
      download_friendly
      __typename
    }
    filters {
      __typename
      key
      title
      type
      options {
        ... on totara_catalog_option {
          __typename
          id
          label
          active
        }
        ... on totara_catalog_tree_option {
          __typename
          id
          parentid
          label
          active
        }
      }
    }
    browse_filter {
      __typename
      key
      title
      type
      options {
        ... on totara_catalog_option {
          __typename
          id
          label
          active
        }
        ... on totara_catalog_tree_option {
          __typename
          id
          parentid
          label
          active
        }
      }
    }
  }
}
