<?php
/**
 * This file is part of Totara Core
 *
 * Copyright (C) 2023 onwards Totara Learning Solutions LTD
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @note Automatically cleaned: 2024-09-24
 * @author Simon Chester <simon.chester@totara.com>
 * @package mfa_totp
 */

$string['component'] = 'MFA authenticator app';
$string['enter_6_digit_code_placeholder'] = 'Enter 6-digit code';
$string['enter_code_instructions'] = 'To continue, please enter the verification code generated by your authenticator app.';
$string['factor_description'] = 'Get a code through a third-party app such as Google or Microsoft Authenticator';
$string['pluginname'] = 'Authenticator app';
$string['register_title'] = 'Add an authenticator app';
$string['setup_help'] = 'Using an authenticator app on your phone, scan the QR code or manually enter the code below.';
$string['task_name'] = 'Clear used TOTP tokens';
$string['token'] = 'Token';
$string['verify_desc'] = 'Enter the 6-digit code generated by your authenticator app.';
$string['verify_title'] = 'Authentication code';

/**
 * Errors
 */
$string['error:invalid_token'] = 'Code is not valid';
