<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = $vendorDir;

return array(
    'SimplePie' => array($vendorDir . '/simplepie/simplepie/library'),
    'Less' => array($vendorDir . '/wikimedia/less.php/lib'),
    'HTMLPurifier' => array($vendorDir . '/ezyang/htmlpurifier/library'),
);
